config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

# DaemonSet으로 모든 노드에서 로그 수집
tolerations:
  - effect: NoSchedule
    operator: Exists

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
