apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-data
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://supabase-community.github.io/supabase-kubernetes
      chart: supabase
      targetRevision: 0.5.6
      helm:
        valueFiles:
          - $values/values/values-data.yaml
    - repoURL: https://github.com/sanggyoon/202605_KakaoCloud_AIaaS.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
