apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: be

resources:
  - deployment.yaml
  - service.yaml
  - backfill-cronjob.yaml
  - subtitle-cronjob.yaml
  - hpa.yaml
  - networkpolicy.yaml

images:
  - name: ghcr.io/sanggyoon/4k-be
    newTag: "e5ed0e4"
