apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: understand

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sanggyoon/understand-dashboard
    newTag: "780d272"
