controller:
  kind: DaemonSet
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    workload: ingress
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  service:
    type: ClusterIP
