apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fe

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/sanggyoon/4k-fe
    newTag: "23ad992"
